### ISSUE TITLE
один файл в архивах

### ISSUE THREAD

**Issue by Ulitochka** [dialogue-evaluation/morphoRuEval-2017#1]
во всех архивах (живой журнал) 1 файл. начинается со слов: че тут обсуждать-то? не много ли чести для всякой хуйни?) и заканчивается: Молодец, что не боится)))

**Comment by TatianaShavrina** [comment]
Да, все верно, файл LiveJournalpostsandcommentsGICR разбит на 10 архивов, так как весит 345 МБ. Там более миллиона строк.
За мат извините, конечно, но таков уж ресурс.

**Comment by Ulitochka** [comment]
вопрос в том, что во всех архивах 1 файл без изменений.

**Comment by TatianaShavrina** [comment]
Эти 10 архивов связаны между собой, так как они автоматически созданы при архивации одного большого файла. Когда Вы распаковываете один, на самом деле задействуются все архивы, иначе Вы бы получили битый файл.
Распакованный файл получается в объеме около 340 МБ, правильно?
Значит, все в порядке.

Это неразмеченный материал ЖЖ, а размеченный лежит вот тут: https://github.com/dialogue-evaluation/morphoRuEval-2017/blob/master/GIKRYA_texts.rar

**Comment by Ulitochka** [comment]
cпасибо.
