### ISSUE TITLE
illustration.txt содержит POS теги не из morphostandard

### ISSUE THREAD

**Issue by kmike** [dialogue-evaluation/morphoRuEval-2017#11]
Например, третье слов - "во" - обозначено как PREP; в morphostandard такой части речи нет.

**Comment by TatianaShavrina** [comment]
Данные в illustration представлялись до того, как были предоставлены основные данные, чтобы найти несостыковки и ошибки, а также представить формат данных.
PREP и многие другие ошибки уже решены и не содержатся в остальных данных.
