### ISSUE TITLE
Проблемы с файлом JZ.txt

### ISSUE THREAD

**Issue by DanAnastasyev** [dialogue-evaluation/morphoRuEval-2017#17]
JZ.txt выглядит несколько битым в одном месте:

![2017-03-15_00-22-30](https://cloud.githubusercontent.com/assets/5503582/23923134/727cc750-0916-11e7-92a2-f0bec3dcffa3.png)

**Comment by TatianaShavrina** [comment]
Перезалила, проверьте.
Теперь должно быть все хорошо
