### ISSUE TITLE
использование скрипта evaluate

### ISSUE THREAD

**Issue by Ulitochka** [dialogue-evaluation/morphoRuEval-2017#19]
Скажите пожалуйста, в описании скрипта есть фраза: "Использование: python evaluate.py [-l|--lemmas] corr_file test_file", то есть corr_file - наш файл, а test_file - файл для тестирования?

**Comment by AlexeySorokin** [comment]
Именно так.

**Comment by Ulitochka** [comment]
coor_file - на чем тестируется, test_file - что тестируется.

**Comment by AlexeySorokin** [comment]
Ой, наоборот, corr --- тот, который корректен, test --- тот, который тестируется (выдача анализатора).
