### ISSUE TITLE
Интересные токены.

### ISSUE THREAD

**Issue by Ulitochka** [dialogue-evaluation/morphoRuEval-2017#20]
Добрый день.
С файле JZ есть такое:
1       С_е_р_г_е_й
2       М
3       а
4       г
5       и
6       д.
7       В
8       долине
9       Элах
10 

Вопрос: так задумано?

**Comment by AlexeySorokin** [comment]
Так не было задумано, но этот текст заведомо не входит в верифицированное вручную подмножество выборки, на котором измеряется качество.
